---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'cloud/**'
      - 'doc/**'
      - 'fuzzer/**'
      - 'ide/**'
      - 'kobo/**'
      - 'python/**'
      - '.github/workflows/build-container.yml'
      - '.github/workflows/build-unix.yml'
      - '.readthedocs.yaml'
    branches:
      - master
      - dev-branch
    tags:
      - 'v*'

  pull_request:
    paths-ignore:
      - 'cloud/**'
      - 'doc/**'
      - 'fuzzer/**'
      - 'ide/**'
      - 'kobo/**'
      - 'python/**'
      - '.github/workflows/build-container.yml'
      - '.github/workflows/build-unix.yml'
      - '.readthedocs.yaml'
    branches:
      - master
      - dev-branch

env:
  DEBUG: y
  BOOST: boost_1_85_0
  # GIT_SHA: GITHUB_SHA
  # GIT_HASH: ${GITHUB_SHA:0:7}
  ### GIT_HASH: $(git rev-parse --short $GITHUB_SHA)

jobs:
  release:
    name: "Create Release"
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Parse changelog
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG=$(echo "${{ github.ref }}" | cut -f3 -d '/')
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo 'CHANGELOGENTRY<<EOF' >> $GITHUB_ENV
          ./tools/changelog.sh "$TAG" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          case "$TAG" in
            *-rc*)
              echo "PRERELEASE=true" >> $GITHUB_ENV
              ;;
            *)
              echo "PRERELEASE=false" >> $GITHUB_ENV
              ;;
          esac
        id: changelogentry

      - name: Create release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1.1.4
        # uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          allowUpdates: true
          name: Version ${{ github.ref_name }}
          body: ${{ env.CHANGELOGENTRY }}
          prerelease: ${{ env.PRERELEASE }}

      - name: Get OpenSoar Version
        id: get_version
        run: |
          echo "Get OpenSoar Version"
          echo "CurrDir = $(pwd)"
          ls -l .
          chmod +x ./ide/github/build.sh
          ./ide/github/build.sh
          ####    # include OpenSoar.config
          ####    # VERSION=$PROGRAM_VERSION
          ####    VERSION=7.43.22.1
          ####    # VERSION=$(cat VERSION.txt)
          ####    echo "$VERSION"
          ####    echo "VERSION=${VERSION}" >> $GITHUB_ENV
          ####    echo "GITHUB_SHA = $GITHUB_SHA"
          ####    echo "GIT_HASH = $GIT_HASH"
          ####    GIT_HASH=$(git rev-parse --short $GITHUB_SHA)
          ####    echo "GIT_HASH = $GIT_HASH"
          ####    GIT_HASH=${GITHUB_SHA:0:7}
          ####    echo "GIT_HASH = $GIT_HASH"
          ####    echo "PRERELEASE = $PRERELEASE"
          ####    echo "GITHUB_ENV = $GITHUB_ENV"
          ####    echo "PRERELEASE = ${{ env.PRERELEASE }}"
          ####    echo "git_hash=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
          ####    echo "GIT_HASH=$GIT_HASH" >> $GITHUB_ENV
          ####    echo "git_hash = ${{ env.git_hash }}"
          ####    echo "git_hash = $git_hash"
          ####    if [ -z ${{ env.git_hash }} ]; then
          ####      echo "git_hash=$(git rev-parse --short --verify HEAD )" >> $GITHUB_ENV
          ####      echo "env.git_hash = '${{ env.git_hash }}'"
          ####    fi 
          ####    echo "GITHUB_ENV = $GITHUB_ENV"
          ####    echo "--------------------"
          ####    echo "cat $GITHUB_ENV"
          ####    cat $GITHUB_ENV
          ####    echo "--------------------"
          ####    echo "cat OpenSoar.config"
          ####    cat OpenSoar.config
          ####    echo "--------------------"

  build:
    runs-on: ${{ matrix.os }}
    needs: release
    container: ${{ matrix.target_container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            target: ANDROIDAARCH64
            target_bin: OpenSoar
            target_bin_path: bin
            target_final: OpenSoar
            target_ext: .apk
            target_test: true
            target_upload: true
            upload_artifact: false
            ndk: r26d
            target_container: debian:bookworm-slim
          
          - os: ubuntu-24.04
            target: ANDROID
            target_bin: OpenSoar
            target_bin_path: bin
            target_final: OpenSoar
            target_ext: .apk
            target_test: false
            target_upload: true
            upload_artifact: true
            ndk: r26d
            target_container: debian:bookworm-slim
# ------------------------------------------------------
          - os: ubuntu-24.04
            target: UNIX
            target_bin: OpenSoar_${{ needs.release.outputs.version }}_amd64
            target_bin_path: ''
            target_final: OpenSoar_
            target_ext: .deb
            target_test: true
            target_upload: true
            upload_artifact: false
            target_container: debian:bookworm-slim
          
          - os: ubuntu-24.04
            target: KOBO
            target_bin: KoboRoot
            target_bin_path: 'bin'
            target_final: KoboRoot
            target_ext: .tgz
            target_upload: true
            upload_artifact: false
            target_container: debian:bookworm-slim
          
          - os: ubuntu-24.04
            target: WIN64
            target_bin: OpenSoar
            target_bin_path: bin
            target_final: OpenSoar
            target_ext: .exe
            target_test: true
            target_upload: true
            upload_artifact: true
            target_container: debian:bookworm-slim
          
          - os: ubuntu-24.04
            target: PC
            target_bin: OpenSoar
            target_bin_path: bin
            target_final: OpenSoar
            target_ext: .exe
            target_test: true
            target_upload: true
            upload_artifact: false
            target_container: debian:bookworm-slim
          
          - os: macos-12
            target: OSX64
            target_bin: OpenSoar
            target_bin_path: bin
            target_final: OpenSoar
            target_ext: ''
            target_test: false
            target_upload: false
            upload_artifact: true
            target_container: ''
          
          - os: macos-14
            target: MACOS
            target_bin: OpenSoar
            target_bin_path: bin
            target_final: OpenSoar
            target_ext: ''
            target_test: true
            target_upload: false
            upload_artifact: false
            target_container: ''
          
          - os: macos-14
            target: IOS64
            target_bin: OpenSoar
            target_bin_path: bin
            target_final: OpenSoar
            target_ext: ''
            target_test: false
            target_upload: false
            upload_artifact: false
            target_container: ''

    steps:
      #### - name: Install checkout dependencies
      ####   if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      ####   run: |
      ####     echo "Install checkout dependencies: ${{ matrix.target }} "
      ####     apt-get update
      ####     apt-get install -y --no-install-recommends git \
      ####       ca-certificates rsync openssh-client

      ### - name: Git clone 
      ###   # if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      ###   run: |
      ###     echo "Git Clone "
      ###     git clone https://github.com/$GITHUB_REPOSITORY
      ###     git reset --hard $GITHUB_SHA
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true


      - name: Check Git Variables
        run: |
          echo "Check Git Variables"
          echo "CurrDir = $(pwd)"
          ls -l .
          chmod +x ./ide/github/build.sh
          ./ide/github/build.sh
        working-directory: ${{ github.workspace }}
          ####    echo "Check git variables"
          ####    echo "CurrDir = $(pwd)"
          ####    echo "github.workspace = ${{ github.workspace }}"
          ####    echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          ####    echo "GITHUB_ENV = $GITHUB_ENV"
          ####    echo "--------------------"
          ####    echo "cat $GITHUB_ENV"
          ####    ## cat ${GITHUB_ENV}
          ####    echo "--------------------"
          ####    echo "GITHUB_REPO = $GITHUB_REPOSITORY"
          ####    echo "GITHUB_SHA = $GITHUB_SHA"
          ####    ## echo ${GITHUB_SHA:0:7}
          ####    ## echo .
          ####    # Bad substitution: GIT_HASH=$(echo ${GITHUB_SHA:0:7} )
          ####    GIT_HASH=$(echo $GITHUB_SHA | head -c 7)
          ####    echo "GIT_HASH = $GIT_HASH"

          ### echo "GIT_HASH = $GIT_SHA"
          ### GIT_HASH=${GITHUB_SHA}
          ### echo "GIT_HASH = $GIT_HASH"
          ### echo "Test:= ${{ github.workspace }}"
          ### echo $GITHUB_SHA | head -c 10
          ### echo .
          ### GIT_HASH=$($GITHUB_SHA | head -c 10)
          ### echo "GIT_HASH = $GIT_HASH"
          ### GIT_HASH=$(echo $GITHUB_SHA | head -c 10)
          ### echo "GIT_HASH = $GIT_HASH"
          ### # echo Test:= $GITHUB_SHA | head -c 10
          ### # GIT_HASH=$(echo  ${{ github.GITHUB_SHA }} | head -c 10)
          ### echo "GIT_HASH = $GIT_HASH"
          ### ###  echo "GIT_HASH = $GIT_HASH"
          ### ###  ### if [ -z '${{ env.git_hash }}' ]; then
          ### ###  ###   echo "git_hash isn't set!!!"
          ### ###  ###   git_hash=$(git rev-parse --short "$GITHUB_SHA")
          ### ###  ###   echo 'git_hash = $(git rev-parse --short "$GITHUB_SHA")' >> $GITHUB_ENV
          ### ###  ###   echo "git_hash = ${{ env.git_hash }}"
          ### ###  ### else
          ### ###  ###   echo "git_hash = ${{ env.git_hash }}"
          ### ###  ###   echo "git_hash = $git_hash"
          ### ###  ### fi
        

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: WIN64
          - os: windows-latest
            target: PC
          - os: ubuntu-
            target: UNIX
          - os: macos-14
            target: MACOS

    needs: build
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - name: Fetch Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Test-${{ matrix.target }}
          path: ${{ github.workspace }}/output/${{ matrix.target }}/bin
      - name: OpenSoar run checks on ${{ matrix.target }}
        run: |
          echo "OpenSoar run checks on ${{ matrix.target }}"
          echo "CurrDir = $(pwd)"
          ls -l .
          chmod +x ./ide/github/build.sh
          ./ide/github/build.sh
          # echo "run tests on Target '${{ matrix.target }}'"
          # make check-no-build TARGET=${{ matrix.target }}
        working-directory: ${{ github.workspace }}
